### ISSUE TITLE
Failure to Start Server

### ISSUE THREAD

**Issue by JLUsr** [Devoev/vanilla-cubed#4]
Fabric-API-0.60.0+1.19.2
Fabric-Language-Kotlin-1.8.3+Kotlin.1.7.10
Vanilla-Cubed-1.19.2-1.2.3
NBTCrafting-2.1.4+mc1.19

It doesn't progress far enough to give a proper crash log but this is what I get from my
[latest.log](https://github.com/Devoev/vanilla-cubed/files/9579261/latest.log)

_Edited to show information for version 2.1.4 (no change to log other than showing NBTCrafting)_

**Comment by Devoev** [comment]
Hmm interesting, I'll look into it in the upcoming days and try to find the cause of the issue. But I haven't done any server side testing so far, so it might take a while until I can fix it. But thanks for the report!

**Comment by Devoev** [comment]
I released a new version (1.4.1) that should hopefully fix the issue. Can you tell me if it works now?

**Comment by JLUsr** [comment]
I can confirm that there is no issue with server launch using 1.4.1
