### ISSUE TITLE
[Suggestion] Item Collection as Enchantment or Config

### ISSUE THREAD

**Issue by JLUsr** [Devoev/vanilla-cubed#5]
Just wanted to suggest making the automatic item collection/magnetism, that occurs when a player holds a tool, into a configurable setting or an enchantment. (Maybe make it only occure whilst crouching if those ideas don't fit the theme of the mod?)

I say this purely because it seems like it could cause issues with players accidentally picking up junk items whilst attempt to pickup specific loot.

**Comment by Devoev** [comment]
Thanks for the suggestion! I already thought about an option to disable the magnetism effect for netherite tools, but haven't decided on a great way to implement it, so that it still feels like vanilla. But I'll definitely change this in one of the next updates.

**Comment by JLUsr** [comment]
Feature accomplished with the latest version. Thank you very much.
