### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Mokeysam** [Devoev/vanilla-cubed#7]
- Cloth Config 8.2.88
- Fabric API 0.63.0
- Fabric Kotlin 1.8.5
- NBTCrafting 2.2.2
- Vanilla-cubed 1.3.2

Server crashes with just these. Any idea how to fix?

**Comment by Devoev** [comment]
Unfortunately no idea yet. There's already another issue regarding server crashing, but I haven't had the time yet, to do any server side testing for the mod. I'll try to look into it during the holiday season, but right know I don't really have time to fix the issue

**Comment by Devoev** [comment]
I released a new version (1.4.1) that should hopefully fix the issue. Can you tell me if it works now?

**Comment by Mokeysam** [comment]
I just installed it onto a server, seems tow work all fine now. Nice work!

**Comment by Devoev** [comment]
You're welcome!
